
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    version: '3.1.200'
- task: DotNetCoreCLI@2
  displayName: Install dotnet-ef
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install --global dotnet-ef'
- task: DotNetCoreCLI@2
  displayName: Check dotnet-ef version
  inputs:
    command: 'custom'
    custom: 'ef'
    arguments: '--version'
- script: ls
  displayName: 'show current resources'

# - task: LambdaNETCoreDeploy@1
#   inputs:
#     awsCredentials: 'tungds-aws'
#     regionName: 'ap-southeast-1'
#     command: 'deployServerless'
#     packageOnly: false
#     lambdaProjectPath: '.'
#     stackName: 'dev-tungds-demo-cshaph'
#     s3Bucket: 'tungds-aws-azure-cf'
#     s3Prefix: 'serverless'
#     additionalArgs: '--template "serverless.yml"'