
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    version: '3.1.200'
- task: DotNetCoreCLI@2
  displayName: Install dotnet-ef
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install --global dotnet-ef'
- task: DotNetCoreCLI@2
  displayName: Check dotnet-ef version
  inputs:
    command: 'custom'
    custom: 'ef'
    arguments: '--version'
- task: LambdaNETCoreDeploy@1
  inputs:
    awsCredentials: 'aws'
    command: 'deployServerless'
    packageOnly: false
    stackName: 'dev-tungds-demo-cshaph'
    s3Bucket: 'ptawsg-dev-nsbucket'
    s3Prefix: 'serverless'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
